# CMake generated Testfile for 
# Source directory: /home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test
# Build directory: /home/plonga/Documents/Faster_Fp_arithmetic/relic-target/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_bn "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_bn")
set_tests_properties(test_bn PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;18;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_dv "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_dv")
set_tests_properties(test_dv PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;22;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_fp "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_fp")
set_tests_properties(test_fp PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;26;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_fpx "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_fpx")
set_tests_properties(test_fpx PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;30;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_ep "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_ep")
set_tests_properties(test_ep PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;42;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_epx "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_epx")
set_tests_properties(test_epx PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;46;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_ec "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_ec")
set_tests_properties(test_ec PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;58;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_pc "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_pc")
set_tests_properties(test_pc PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;62;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_pp "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_pp")
set_tests_properties(test_pp PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;66;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_md "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_md")
set_tests_properties(test_md PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;70;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_cp "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_cp")
set_tests_properties(test_cp PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;74;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_rand "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_rand")
set_tests_properties(test_rand PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;81;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
add_test(test_core "/home/plonga/Documents/Faster_Fp_arithmetic/relic-target/bin/test_core")
set_tests_properties(test_core PROPERTIES  _BACKTRACE_TRIPLES "/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;10;add_test;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;82;ADD_MODULE;/home/plonga/Documents/Faster_Fp_arithmetic/GitHub_faster_Fp_arithmetic/Pairings/relic/test/CMakeLists.txt;0;")
